### ISSUE TITLE
An Issue downloading Coursera Videos as well

### ISSUE THREAD

**Issue by rahiduddin** [bcbcbcbcbcl/working-coursera-download-with-selenium#3]
Maybe I'm dumb I don't know honestly so I'm using my Raspberry Pi 3 on Ubuntu Mate to do this since I'm not sure how to do it on WIndows but I'm getting some error?

**Comment by rahiduddin** [comment]
I just read the update it's outdated due to Google Captcha shucks darn it :( thank you for creating this though I don't even understand how you or any programmers do this hence why I'm not considering computer science or IT anymore

**Comment by bcbcbcbcbcl** [comment]
Although this repo is outdated and not maintained anymore, the error shown in the image could be due to you are using Python2 or the webdriver is not supported on Ubuntu Mate. 

Kind reminder: please remove the image above as you're showing your login credentials there.
